// Converts src/lib/mole-fractions.csv → src/lib/mole-fractions.ts.
// Usage: npx tsx scripts/csv-to-ts.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root    = resolve(import.meta.dirname, '..');
const csvPath = resolve(root, 'src/lib/mole-fractions.csv');
const tsPath  = resolve(root, 'src/lib/mole-fractions.ts');

const lines = readFileSync(csvPath, 'utf8').trim().split('\n');
const header = lines[0]!.split(',');

// Species columns start after altitude and molar_mass.
const species = header.slice(2);

const rows: string[] = [];
for (let i = 1; i < lines.length; i++) {
    const cols = lines[i]!.split(',');
    rows.push(`  [${cols.join(',')}]`);
}

const out = `\
// Auto-generated by: npx tsx scripts/csv-to-ts.ts
// Do not edit manually.
export const MF_SPECIES = [${species.map(s => `'${s}'`).join(',')}] as const;
export type MFSpecies = typeof MF_SPECIES[number];
// Each row: [altitude_m, molar_mass_g_per_mol (= kg/kmol), ...mole_fractions_in_MF_SPECIES_order]
export const MF_DATA: readonly (readonly number[])[] = [
${rows.join(',\n')},
];
`;

writeFileSync(tsPath, out);
console.log(`Written ${rows.length} rows to ${tsPath}`);
